repository: Sachin-Kottarathodi/sachinkottarathodi.github.io
url: "https://sachinkottarathodi.github.io"
baseurl: 

title: "Sachin Kottarathodi's Portfolio"
author: "Sachin Kottarathodi"
theme: minima