title: "Sachin Kottarathodi's Portfolio"
author: "Sachin Kottarathodi"
theme: minima

repository: Sachin-Kottarathodi/sachinkottarathodi.github.io
url: "https://sachin-kottarathodi.github.io"
baseurl: "/sachinkottarathodi.github.io"
